### ISSUE TITLE
Can't deploy function when using code as is

### ISSUE THREAD

**Issue by LukeHosk** [supabase-community/expo-stripe-payments-with-supabase-functions#6]
# Bug report

## Describe the bug

Tried implementing the code using the steps you provided, but the deploy step fails with the following message

`Bundling payment-sheet
Error: Error bundling function: exit status 1
file:///src/index.ts
file:///_utils/stripe.ts
file:///_utils/supabase.ts
file:///_utils/db_types.ts
error: Uncaught (in promise) Error: Relative import path "http" not prefixed with / or ./ or ../
      const ret = new Error(getStringFromWasm0(arg0, arg1));
                  ^
    at __wbg_new_8d2af00bc1e329ee (https://deno.land/x/eszip@v0.30.0/eszip_wasm.generated.js:312:19)
    at <anonymous> (https://deno.land/x/eszip@v0.30.0/eszip_wasm_bg.wasm:1:79439)
    at <anonymous> (https://deno.land/x/eszip@v0.30.0/eszip_wasm_bg.wasm:1:1388039)
    at <anonymous> (https://deno.land/x/eszip@v0.30.0/eszip_wasm_bg.wasm:1:1862894)
    at __wbg_adapter_18 (https://deno.land/x/eszip@v0.30.0/eszip_wasm.generated.js:146:6)
    at real (https://deno.land/x/eszip@v0.30.0/eszip_wasm.generated.js:130:14)`

## To Reproduce

1. clone repo to empty dir
2. setup new project
3. created the .env files and filled in my personal values
4. login to my project
5. link my project
6. set my secrets
7. listing secrets and delpoying the "hello" function works as expected
8. run 'supabase functions deploy payment-sheet' 

## Expected behavior

function deploys instead of throwing an error

## System information

- OS: Wondows
- Browser (if applies) Chrome - dont think it applies
- Version of supabase-js: 2.0.0
- Version of Node.js: 8.6.0

**Comment by thorwebdev** [comment]
@LukeHosk ah sorry, we're missing the `no-check` flag in the import: `import Stripe from "https://esm.sh/stripe@10.13.0?target=deno&deno-std=0.132.0&no-check";`
